/**
 * On-chain symbols of the purchasable products, in the routes table's order.
 * Generated by `scripts/routes/add-routes.mjs` from `routes-table.ts`; a
 * routes-table test requires both to agree. It imports nothing, so a page
 * can state the list without loading the purchase code.
 */
export const PRODUCT_SYMBOLS = ["NVDAx", "METAx", "MSTRx", "GOOGLx", "CRCLx", "TSLAx", "SPYx", "HOODx", "AMDx", "COINx", "AMZNx", "MSFTx", "QQQx", "GLDx", "BRK.Bx", "AVGOx", "MCDx", "KOx", "INTCx", "UNHx", "XOMx", "PLTRx", "GMEx", "STRCx", "WMTx"] as const;
